main: Main.Mains
name: CompressedPlugIns
version: 1.7.0
api-version : 1.16
description : none
commands:
   store:
      description: Base Store Commands
      usage: /store StoreName
   evt:
      description: For Event Store Commands
      usage: /evt StoreName